<Project Sdk="Microsoft.NET.Sdk.Web">


	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>supermarket-web-8f2a1e4c-9b3d-4a7f-9c1e-2d6b7a5e0f31</UserSecretsId>

		<!-- این دو خط حیاتی هستند تا فایل‌های مرجع برای کامپایلر Razor در دسترس قرار گیرند -->
		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperMarket.Application\SuperMarket.Application.csproj" />
    <ProjectReference Include="..\SuperMarket.Infrastructure\SuperMarket.Infrastructure.csproj" />
  </ItemGroup>

</Project>
